version: 1.0.{build}
image: Visual Studio 2019
environment:
  URL:
    secure: f4DzuARrHNBCCfE+ps9Y5iPSbaIn5S7PLkz6ATiLSYnYUea+L/ddEmuPLLJ/i1Re
build_script:
- cmd: |
    appveyor DownloadFile https://github.com/maxim-zhao/sms-build-tools/releases/download/1.0.102/tools.7z
    7z x tools.7z -otools
    path %cd%\tools;%path%
    appveyor DownloadFile -Url %URL% -FileName ps.zip
    7z x ps.zip -opsrp
    cd psrp
    py -m pip install PyYAML
    make LANGUAGE=en
    make clean
    7z a ..\psrp.zip *.?ps ..\readme.md
artifacts:
- path: psrp.zip
  name: psrp
